# LD_FILE = boards/samd51x19-bootloader.ld

USB_VID = 0x239A
USB_PID = 0x8026

USB_PRODUCT = "Doppler"
USB_MANUFACTURER = "dadamachines"

CHIP_VARIANT = SAMD51G19A
CHIP_FAMILY = samd51

INTERNAL_FLASH_FILESYSTEM = 1
LONGINT_IMPL = NONE
CIRCUITPY_FULL_BUILD = 0

# CIRCUITPY_PS2IO = 0
# # No I2S on SAMD51G
# CIRCUITPY_AUDIOBUSIO = 0
# # No touch on SAMD51 yet
# CIRCUITPY_TOUCHIO = 0

# CIRCUITPY_DISPLAYIO = 0